server:
  port: 8080

spring:
  application:
    name: organice-lembrete
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Post123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: lembrete
  jpa:
    properties:
      hibernate:
        default_schema: lembrete
  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"

springdoc:
  api-docs:
    path: /lembretes/v3/api-docs
  swagger-ui:
    path: /lembretes/swagger-ui.html


# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      base-path: /lembretes/actuator
      exposure:
        include: [ 'prometheus' ]