spring:
  application:
    name: organice-lembrete
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/organice}
    username: ${DATABASE_USERNAME:organice}
    password: ${DATABASE_PASSWORD:organice123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: lembrete
  jpa:
    properties:
      hibernate:
        default_schema: lembrete
  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"

springdoc:
  api-docs:
    path: /lembretes/v3/api-docs
  swagger-ui:
    path: /lembretes/swagger-ui.html


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}