apiVersion: v1
kind: Service
metadata:
  name: lembrete
  labels:
    name: lembrete
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: lembrete